### ISSUE TITLE
Suddenly everything is not connected anymore

### ISSUE THREAD

**Issue by LeGreatMaxiking** [Breina/PowerTagGateway#12]
Hey, got your integration working for a few months, now suddenly all entitys are gone and when i try to delete the devices and re add them they are connecting but wont creating any devices or entitys any fix for that?

**Comment by Breina** [comment]
Did you update or do anything special? Can you still login to the gateway through the web interface and check that your wireless devices are connected?

**Comment by Breina** [comment]
Closing issue: no further input.
