### ISSUE TITLE
Gateway support

### ISSUE THREAD

**Issue by killernils** [Breina/PowerTagGateway#13]
Hi, is the CCT501901 gateway supported? It comes bundled with a A9MEM1570 powertag in Sweden.
Or I need e.g the PAS400 instead?

Thanks in advance!

**Comment by Breina** [comment]
Yeah I'm afraid that you'll need a panel server instead. The CCT501901 gateway doesn't seem to have any kind of accessible API. :(

**Comment by Breina** [comment]
Closing issue: support not possible.
