### ISSUE TITLE
 Integration entries not populating devices/entities

### ISSUE THREAD

**Issue by DobrCr** [Breina/PowerTagGateway#18]
Hello, I have two Acti9 PowerTag Link HD - Wireless to Modbus TCP/IP Concentrators (A9XMWD100) and some power meters connected to them:
- A9MEM1520
- A9MEM1540
- A9MEM1580
- A9MEM1591

This might be the same or similar problem to issue #15...?

When I try to connect either A9XMWD100, I encounter a problem. The automatic DPWS discovery finds both of them and I can add them to the integration (v0.2.2).

I get to a problem at this stage. One of the meters seems to get connected fine but the other doesn't - no devices or entities (attached screenshot):
![image](https://github.com/Breina/PowerTagGateway/assets/58089686/e2871436-5e72-4055-8f99-2f33f43762fa)

You asked for logs in issue #15 to troubleshoot, so I am attaching the logs I get.
![image](https://github.com/Breina/PowerTagGateway/assets/58089686/0fc20d76-4985-4b22-9ef9-701d8484df79)

Also attaching the [full logs](https://github.com/Breina/PowerTagGateway/files/15008808/HA.log.for.EcoStruxure.PowerTag.Link.Gateway.v0.2.2.txt).

If you need any additional logs or further information, please do tell. I'll be happy to provide so  we can troubleshoot the problem.

**Comment by Breina** [comment]
Hi, thanks for being so forward to provide the logs immediately! :)

It crashes right when it's querying your device's usage. Is it possible that this wasn't configured yet on your powertags?

I also fixed a logging issue, can you please update to v0.2.3 and attach the logs again?

**Comment by DobrCr** [comment]
Thanks for a speedy response and update.

I've updated and there is some progress. The PowerTagLink-Pisarna was populated with a lot more entities (from 2 on v0.2.2 to 65 on v0.2.3). The other PowerTag remains unpopulated. I've deleted it and re-added it with DPWS discovery with the hope it might help, but no change:
![image](https://github.com/Breina/PowerTagGateway/assets/58089686/84366c33-8774-44c3-93ad-da2b28322a3e)

Here are the new [logs](https://github.com/Breina/PowerTagGateway/files/15021062/home-assistant_2024-04-18T06-59-57.868Z.log).

If I connect to PowerTagLinks directly there is data from the connected power meters. ([Here](https://github.com/Breina/PowerTagGateway/assets/58089686/f3a6f988-dae8-4ff4-898d-99bbd1d9dd72)) is an example from the one that's not being populated with any entities (Proizvodnja).

I have just double checked their settings and both have been configured the exact same way except for the IPv6 setting. The one that's causing problems has IPv6 set/checked. You mentioned this might cause problems for Panel Server only and not for PowerTag Link devices under Installation/preparation. Should I disable IPv6 (we don't need it) and try again?

**Comment by DobrCr** [comment]
Small update that might provide additional information for troubleshooting.

I've installed HA on Hyper-V to try and connect with PowerTags with a unmodified fresh installation of HA. I get the same problem. The same PowerTag (Pisarna) connects and populates devices/entities without a problem and the other one (Proizvodnja) again gives "No devices or entities".

There is a connection to both though, because ATM I'm off site and both PowerTags give an error "_Failed setup, will retry_" with a pop-up `Modbus Error: [connection] Failed to connect[ModbusTcpClient(IP:PORT)]`, which is expected since I'm not on site. But it shows that when onsite, it connects to both devices at least partially?

**Comment by Breina** [comment]
Alright I released v0.2.4 for you, please try it out and check if it fixes the problem. :)

**Comment by DobrCr** [comment]
Very thankful for the help!

Unfortunately, something broke and the situation is worse than before. Devices "fail to set up".
![Screenshot 2024-04-30 110139](https://github.com/Breina/PowerTagGateway/assets/58089686/3dbc3174-e842-43ad-abef-d570daa61f96)

I tried removing and adding back a device (Proizvodnja) and even that broke. When trying to add with DPWS discovery I get an error:
![Screenshot 2024-04-30 110436](https://github.com/Breina/PowerTagGateway/assets/58089686/8b3a2137-9aab-4aaf-892d-cd8431a1d638)

When trying to add manually I get a "Failed to connect".


Attaching multiple logs since they aren't the same:
- [1st log](https://github.com/Breina/PowerTagGateway/files/15161197/home-assistant_2024-04-30T09-02-56.209Z.log) after updating to v0.2.4 and HA restart (1st screenshot above).
- [2nd log](https://github.com/Breina/PowerTagGateway/files/15161225/home-assistant_2024-04-30T09-04-57.668Z.log) was downloaded sometime in between 1st and 3rd, but I'm not sure what the state of restarting, removing, adding of devices was.
- [3rd log](https://github.com/Breina/PowerTagGateway/files/15161208/home-assistant_2024-04-30T09-17-41.695Z.log) after removing PowerTagLink-Proizvodnja and trying to add it back, restarting HA for the second time and trying to add it once more.

I'm sorry for the confusing state of logs. Hopefully more information, even though confusing, might help to troubleshoot.

**Comment by Breina** [comment]
Shit sorry, I have fat fingers. Please check out v0.2.5.

**Comment by DobrCr** [comment]
No worries. All the help is very much appreciated. Thank you for the quick response too.

I've just updated to v.0.2.5 and we made some progress! The other gateway (renamed from Proizvodnja to PRZV between the updates) now connects successfully (at least it looks so) and shows data for a few devices, but not all. There are 28 meters connected to the gateway and only 11 show up (12 are shown on the screenshot because 11 meters + 1 gateway).

![image](https://github.com/Breina/PowerTagGateway/assets/58089686/4904f217-32ca-4651-8fd9-f07825dcf8fc)

When looking at the 11 devices connected some say "wireless communication valid". I'm guessing this the default value and not a bug, right? Because I've not named all the devices connected the meters. For example, I have named the "Pakirka" device which is shown on the screenshot attached below. If it's working as intended, then all good.

![image](https://github.com/Breina/PowerTagGateway/assets/58089686/bd5b92f5-3a40-4062-b7c5-a4c5452b4103)

I'm attaching current logs for further debugging: [HA_PowerTagGateway_v0.2.5_2024-05-03.log](https://github.com/Breina/PowerTagGateway/files/15199941/HA_PowerTagGateway_v0.2.5_2024-05-03.log)

**Comment by Breina** [comment]
Please check out v0.3.0. :)

**Comment by DobrCr** [comment]
Amazing job! You've done it. All the meters are connected and read now.

![image](https://github.com/Breina/PowerTagGateway/assets/58089686/31948f66-6e0b-437b-9713-d39dd0af2c07)

There are some errors still present, but they don't seem critical.

One error is repeated many times and there is one unique error:
![image](https://github.com/Breina/PowerTagGateway/assets/58089686/2a277a72-a6a1-4290-8635-373127329567)

Attaching the full logs: [HA_PowerTagGateway_v3.0.0_2024-05-06.log](https://github.com/Breina/PowerTagGateway/files/15217682/HA_PowerTagGateway_v3.0.0_2024-05-06.log)


I'm not sure if this is fixable from our end though...

**Comment by Breina** [comment]
Happy to hear! :)

The temperature ones, I can fix, but that would result in people's state history being invalidated and a different warning will be shown.

The reactive energy (VAh) isn't a unit that is supported by HA yet, so I have to lobby that one. I'll do all of this type of warnings at once.

**Comment by Breina** [comment]
Just for reference, there's some active discussion for supporting VAh and varh; https://github.com/home-assistant/architecture/discussions/724
