### ISSUE TITLE
New problem with V0.4.2

### ISSUE THREAD

**Issue by kelddamsbo** [Breina/PowerTagGateway#21]
It stopped working when I upgraded to V0.4.2.
I tried to uninstall it from Integration and HACS.
But when I installed it again, it was ok in HACS, but when adding the integration I get the error:

Konfigurationsflow kunne ikke indlæses: {"message":"Invalid handler specified"}

**Comment by Breina** [comment]
Oh shit I see it. Some debug things were left in. Sorry about it!

**Comment by kelddamsbo** [comment]
Thanks again for quick response, and a very good Integration
