### ISSUE TITLE
Missing counters

### ISSUE THREAD

**Issue by kelddamsbo** [Breina/PowerTagGateway#22]
**Describe the bug**
The following sensors is not received from my PAS600, they are just shown as unknown in HA:

![Sensor HA PAS600](https://github.com/Breina/PowerTagGateway/assets/121604835/0c1989a8-24bf-4e90-8983-a78ec97bf283)
sensor.jordvarme_total_active_energy_phase_phase_a
sensor.jordvarme_total_active_energy_phase_phase_b
sensor.jordvarme_total_active_energy_phase_phase_c

I can see them on my PAS600:

Active energy A delivered 230Wh
Active energy B delivered 0Wh
Active energy C delivered 631Wh

**Versions**
 - HomeAssistant: 
Core 2024.5.5
Supervisor 2024.05.1
Operating System 12.3
Brugerflade 20240501.1
Integration: v0.4.3

**Comment by kelddamsbo** [comment]
Forgot to write, the module is a A9MEM1570

**Comment by Breina** [comment]
`A9MEM1570` is part of device class F1:

![image](https://github.com/Breina/PowerTagGateway/assets/3009914/0e69f0ce-4b90-4491-a300-ac194b574b9c)

And F1 should not have phase specific energy data:

![image](https://github.com/Breina/PowerTagGateway/assets/3009914/9b35d807-e4a3-4be1-8889-703ce1e3f4e4)

But the documentation has been wrong in the past (i.e. we shouldn't have device temperature either). I've tested it on my device class A1 devices, and indeed they do seem to work!

I should note though that the `total active energy phase` entities referred to legacy addresses back on the PowerTag Link. The ones that I'll add now are for `total active energy delivered phase` and `total active energy received phase` separately.

**Comment by kelddamsbo** [comment]
I think the doc is wrong, the datasheet for this device says it can messure pr. phase.
This also match what I see in my Panel Server PAS600:
Active energy A delivered 664 Wh
Active energy A delivered non resettable 664 Wh
Active energy A received 0 Wh
Active energy A received non resettable 0 Wh
Active energy B delivered 300 Wh
Active energy B delivered non resettable 300 Wh
Active energy B received 0 Wh
Active energy B received non resettable 0 Wh
Active energy C delivered 3 777 Wh
Active energy C delivered non resettable 3 777 Wh
Active energy C received 0 Wh
Active energy C received non resettable 0 Wh

**Comment by Breina** [comment]
Please check out v0.5.0! :)

**Comment by kelddamsbo** [comment]
It works, thank you a lot, I'm very happy now.
I have another powertag, same type, there are 3 different household on the 3 phases, that's why I really apreciate you brillant work

**Comment by kelddamsbo** [comment]
Solved very quick, thanks a lot
