### ISSUE TITLE
False alarms

### ISSUE THREAD

**Issue by kelddamsbo** [Breina/PowerTagGateway#23]
**Describe the bug**
I always get false alarms on my powertags, see attached picture.
![Alarm Schneider](https://github.com/Breina/PowerTagGateway/assets/121604835/a2dd3e66-0d67-4018-9466-4428e9ee8ed9)
These alarms are activated on my PAS600 on all powertags:
![Alarms activated](https://github.com/Breina/PowerTagGateway/assets/121604835/6aa0c5a9-4f3f-43af-b9ef-8e6f47a32ced)

I have a PAS600 as panel server with SW ver. "esxp-pas-universal-v1-1.9.0.sedp"
I have 5 powertags:
2 x A9MEM1560
3 x A9MEM1570

**Versions**
- Core 2024.6.3
- Supervisor 2024.06.0
- Operating System 12.3
- Brugerflade 20240610.1
- Integration: v0.5.0

**Comment by Breina** [comment]
Fixed in v0.5.1, please verify.

**Comment by kelddamsbo** [comment]
Yes fixed, thank you very much
