### ISSUE TITLE
CL110 False Humidity Reading

### ISSUE THREAD

**Issue by sweidinger** [Breina/PowerTagGateway#24]
**Describe the bug**
The humidity for the CL110 Sensor is missing the factor x100. I'm not sure if this is a problem with HomeAssistant.
The displayed humidity in HA is "0,5512 %" an in PanelServer "55.12 %".

**Versions**
 - HomeAssistant: 2024.6.3
 - Integration: v0.5.0

**Logs**
- [ ] Attached logs to this issue

**Comment by Breina** [comment]
Fixed in v0.5.1, please verify.

**Comment by sweidinger** [comment]
Perfect. Thanks 👍
