### ISSUE TITLE
Gateways beeing discontinued

### ISSUE THREAD

**Issue by Leandrial** [Breina/PowerTagGateway#4]
Hi

Super integration that works really well...

The gateways that are supported are beeing dicontinued thou... so I was wondering if the replacement product will be worked into this integration?

Also, i am in a position where i have access to this line of products.. so if I can help, reach out to me...

Best regards

Leandrial

**Comment by Breina** [comment]
Yes! I would absolutely love to integrate the new line of panel servers (#3).

Let's discuss further in private: info@breina.be

**Comment by Leandrial** [comment]
.
