### ISSUE TITLE
Unable to import component: No module named 'pymodbus.client.sync'

### ISSUE THREAD

**Issue by AlRiachi** [Breina/PowerTagGateway#6]
After updating the Home assistant version to 2023.2.0, I started receiving errors in the logs (Unable to import component: No module named 'pymodbus.client.sync').

The integration is not loaded, and all sensors became NA.

Appreciate your efforts and your commitment to solving this issue.

Home Assistant 2023.2.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230201.0 - latest

Thanks

**Comment by Breina** [comment]
Thanks for the good bug report!

Fixed in v0.1.2
